import { Manrope } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Providers from "./providers";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata = {
  title: "Telegram Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={manrope.variable} lang="en">
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        ></Script>
      </head>
      <body>
        <Providers>
          <main className="wrapper">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
